name: Node.js CI

on:
#  push:
  watch:
    types: [started]
  schedule:
    - cron: 50 23 * * *
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      env:
        WEB_USER: ${{ secrets.WEB_USER }}
        WEB_PWD:  ${{ secrets.WEB_PWD }}
      run: |
          npm install puppeteer
          bash ec2.sh
