name: Node.js CI

on:
#  push:
  watch:
    types: [started]
  schedule:
    - cron: 50 4,10,23 * * *
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      env:
        WEB_USER: ${{ secrets.WEB_USER }}
        WEB_PWD:  ${{ secrets.WEB_PWD }}
      run: |
          npm install puppeteer
          node ./cli.js
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          mv ./.aws/ ~/
          bash ec2.sh
